//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excursion.Portail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Excursion.Portail.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new reservation.
        /// </summary>
        public static string addCaption {
            get {
                return ResourceManager.GetString("addCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string addtext {
            get {
                return ResourceManager.GetString("addtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Booking.
        /// </summary>
        public static string AjouterReservation {
            get {
                return ResourceManager.GetString("AjouterReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Annuler {
            get {
                return ResourceManager.GetString("Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string Chambre {
            get {
                return ResourceManager.GetString("Chambre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the period.
        /// </summary>
        public static string ChoixPeriode {
            get {
                return ResourceManager.GetString("ChoixPeriode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Payment.
        /// </summary>
        public static string DatePayement {
            get {
                return ResourceManager.GetString("DatePayement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Booking.
        /// </summary>
        public static string DateReservation {
            get {
                return ResourceManager.GetString("DateReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected row.
        /// </summary>
        public static string delcaption {
            get {
                return ResourceManager.GetString("delcaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this reservation ?.
        /// </summary>
        public static string delmsg {
            get {
                return ResourceManager.GetString("delmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string deltext {
            get {
                return ResourceManager.GetString("deltext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit selected row.
        /// </summary>
        public static string editCaption {
            get {
                return ResourceManager.GetString("editCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edittext {
            get {
                return ResourceManager.GetString("edittext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip.
        /// </summary>
        public static string Excursion {
            get {
                return ResourceManager.GetString("Excursion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excursions.
        /// </summary>
        public static string Excursions {
            get {
                return ResourceManager.GetString("Excursions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        public static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string LangArab {
            get {
                return ResourceManager.GetString("LangArab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LangEnglish {
            get {
                return ResourceManager.GetString("LangEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        public static string LangFrench {
            get {
                return ResourceManager.GetString("LangFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        public static string LangGerman {
            get {
                return ResourceManager.GetString("LangGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italiano.
        /// </summary>
        public static string LangItalian {
            get {
                return ResourceManager.GetString("LangItalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Langue {
            get {
                return ResourceManager.GetString("Langue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your logo Here Eng.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Modifier {
            get {
                return ResourceManager.GetString("Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adults.
        /// </summary>
        public static string NombreAdultes {
            get {
                return ResourceManager.GetString("NombreAdultes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Babies.
        /// </summary>
        public static string NombreBebes {
            get {
                return ResourceManager.GetString("NombreBebes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        public static string NombreEnfants {
            get {
                return ResourceManager.GetString("NombreEnfants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Number.
        /// </summary>
        public static string NumeroTicket {
            get {
                return ResourceManager.GetString("NumeroTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation.
        /// </summary>
        public static string Observation {
            get {
                return ResourceManager.GetString("Observation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string PasswordCurrent {
            get {
                return ResourceManager.GetString("PasswordCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string PasswordNew {
            get {
                return ResourceManager.GetString("PasswordNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string PasswordNewConfirm {
            get {
                return ResourceManager.GetString("PasswordNewConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string Paye {
            get {
                return ResourceManager.GetString("Paye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting point.
        /// </summary>
        public static string PointDepart {
            get {
                return ResourceManager.GetString("PointDepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Rechercher {
            get {
                return ResourceManager.GetString("Rechercher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations.
        /// </summary>
        public static string Reservations {
            get {
                return ResourceManager.GetString("Reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by destination.
        /// </summary>
        public static string SearchByDestination {
            get {
                return ResourceManager.GetString("SearchByDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a template for multilanguage sites. Use it..
        /// </summary>
        public static string Slogan {
            get {
                return ResourceManager.GetString("Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English example.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string ValidationLengthError {
            get {
                return ResourceManager.GetString("ValidationLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string ValidationPasswordsDontMatch {
            get {
                return ResourceManager.GetString("ValidationPasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
